export const FETCH_HEADLINES_SUCCESS = 'FETCH_HEADLINES_SUCCESS';
export const NEWS_FETCH_FAILURE = 'NEWS_FETCH_FAILURE';
export const FETCH_APPLE_NEWS_SUCCESS = 'FETCH_APPLE_NEWS_SUCCESS';
export const FETCH_BUSINESS_NEWS_SUCCESS = 'FETCH_BUSINESS_NEWS_SUCCESS';
export const FETCH_SPORTS_NEWS_SUCCESS = 'FETCH_SPORTS_NEWS_SUCCESS';
export const FETCH_SAMSUNG_NEWS_SUCCESS = 'FETCH_SAMSUNG_NEWS_SUCCESS';
export const FETCH_ENTERTAINMENT_NEWS_SUCCESS =
  'FETCH_ENTERTAINMENT_NEWS_SUCCESS';
export const USER_IS_SEARCHING = 'USER_IS_SEARCHING';
export const USER_IS_NOLONGER_SEARCHING = 'USER_IS_NOLONGER_SEARCHING';
export const SEARCHING_ERROR = 'SEARCHING_ERROR';
export const USER_SEARCH_RESULTS = 'USER_SEARCH_RESULTS';
export const CHANGE_LANG = 'CHANGE_LANG';
